version: '3'
services:
  
  rabbitmq:
    image: rabbitmq:management
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=OnlineJudge
      - RABBITMQ_DEFAULT_PASS=OnlineJudge
    ports: ["5672:5672", "15672:15672"]

  judger:
    image: registry.cn-hangzhou.aliyuncs.com/philogag/oj-judger:latest
    restart: always
    volumes:
      - "./Judger/language.json:/Judger/language.json"
      - "./Judger/conf.json:/Judger/conf.json"
      - "./Judger/ProblemData:/Judger/ProblemData"
      - "./Judger/Spj:/Judger/Spj"
      - "./Judger/lib/Return.py:/Judger/lib/Return.py"
    depends_on:
      - rabbitmq
    links:
      - rabbitmq:rabbitmq
    tty: true
