# Generated by Django 2.2.11 on 2020-03-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judge_method', models.CharField(max_length=10)),
                ('pid', models.IntegerField()),
                ('ptitle', models.CharField(default='', max_length=50)),
                ('contestid', models.IntegerField(default=-1)),
                ('username', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('lang', models.CharField(choices=[('c++', 'C++'), ('c', 'C'), ('java', 'JAVA'), ('py2', 'Python2'), ('py3', 'Python3')], max_length=10)),
                ('code', models.CharField(max_length=1048576)),
                ('statue', models.IntegerField(choices=[(0, 'ACCEPT'), (1, 'COMPILE_ERROR'), (2, 'TIME_LIMIT_EXCEEDED'), (3, 'MEMORY_LIMIT_EXCEEDED'), (4, 'RUNTIME_ERROR'), (5, 'SYSTEM_ERROR'), (6, 'FORMAT_ERROR'), (7, 'WRONG_ANSWER'), (8, 'MULTI_ERROR'), (-1, 'JUDGING'), (-2, 'WAITING')])),
                ('judger', models.CharField(default='localhost', max_length=20)),
                ('statue_detail', models.CharField(default='', max_length=1048576)),
                ('judger_msg', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
